### ISSUE TITLE
Centos as Host OS

### ISSUE THREAD

**Issue by funky81** [sguyennet/terraform-vsphere-kubespray#1]
Hi, thanks for the guide and code for this.
Just wondering, if I'm using centos, which part that I should change to make it compatible with centos 

Thanks

**Comment by sguyennet** [comment]
Hi,

You should modify the first parameter of the Kubespray configuration template to "centos" instead of "ubuntu":
https://github.com/sguyennet/terraform-vsphere-kubespray/blob/master/templates/kubespray_all.tpl

The second thing is that will be different is the VM template itself. Be careful because I believe that CentOS doesn't install the open-vm-tools automatically. You will have to install them during the creation of the VM template. The open-vm-tools are used by Terraform to customize the VM (network configuration, etc.). Without them inside the template the Terraform deployment will fail.

Let me know if you have an issue. I never tested it myself but I can do a quick lab around this if needed (it is not the first time someone ask me about CentOS :D ).

Have a good weekend,

Simon.

**Comment by funky81** [comment]
Thanks for your feedback..

> You should modify the first parameter of the Kubespray configuration template to "centos" instead of "ubuntu":
https://github.com/sguyennet/terraform-vsphere-kubespray/blob/master/templates/kubespray_all.tpl

noted for this, i have successfuly change

> The second thing is that will be different is the VM template itself. Be careful because I believe that CentOS doesn't install the open-vm-tools automatically. You will have to install them during the creation of the VM template. The open-vm-tools are used by Terraform to customize the VM (network configuration, etc.). Without them inside the template the Terraform deployment will fail.

Noted also, the VM already successfully installed the VMware-Tools.

Last thing is that there's script when installing HAproxy server, and i've got

> sudo: apt-get: command not found

Since I'm using Centos, have to change this into yum. Feedback very welcome

Thanks

**Comment by funky81** [comment]
Hi, now I have change the apropriate file, to change apt-get command into yum.
but now I got error like in below

> Using /root/terraform-vsphere-kubespray/kubespray/ansible.cfg as config file
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
> The error appears to have been in '/root/terraform-vsphere-kubespray/kubespray/roles/vault/handlers/main.yml': line 44, column 3, but may
> be elsewhere in the file depending on the exact syntax problem.
> The offending line appears to be:
> 
> 
> - name: unseal vault
>   ^ here

Any solutions for this?

Thanks

**Comment by funky81** [comment]
Done, i already found out the solution

**Comment by sguyennet** [comment]
Good to know you managed to have it working on CentOS. I forgot about the HAProxy configuration which is done as an inline in the Terraform script. I should probably modify this as it is not very clean.

**Comment by funky81** [comment]
Yup, thanks ...already use this script.
Working flawlessly. Thanks
